version: '3'
services:
#  privacy-idea-ldap-proxy:
#    image: privacy-idea-ldap-proxy:latest
#    volumes:
#      - "/opt/privacyIdeaLDAPProxy:/opt/privacyIdeaLDAPProxy"
#    restart: always
#    ports:
#      - "1389:1389"
#    networks:
#      app_net:
#        ipv4_address: 172.17.0.250

  privacy-idea:
    volumes:
      - "privacyidea_data:/etc/privacyidea"
      - "privacyidea_log:/var/log/privacyidea"
      - "privacyidea_mariadb:/var/lib/mysql"
    restart: always
    image: zetalliance/privacy-idea:latest
    ports:
      - "5000:80"
    networks:
      app_net:
        ipv4_address: 172.17.0.252
        
networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.17.0.0/24

